version: "3.8"

services:
  backend-alticci-sequence:
    image: ellian/alticci-sequence-service:latest
    container_name: alticci-sequence-service
    restart: always
    environment:
      REDIS_HOST: redis://redis-cache:6379
    ports:
      - '8080:8080'
  redis:
    image: redis:alpine
    container_name: redis-cache
    restart: always
    ports:
      - '6379:6379'

networks:
  alticci-sequence:
    driver: bridge
  default:
    name: alticci-sequence
